export { CoursesPage } from "./HeaderPages/CouresPage.async";
export { CourseDetailPage } from "./HeaderPages/CourseDetailPage.async";
export { InfoPage } from "./HeaderPages/InfoPage.async";
export { Main } from "./Main/Main.async";
export { Frontend } from "./Main/directions/Frontend.async";
export { TD } from "./Main/directions/TD.async";
export { SisAdm } from "./Main/directions/SisAdm.async";
export { Backend } from "./Main/directions/Backend.async";
export { MechRob } from "./Main/directions/MechRob.async";
export { MobileDevelopment } from "./Main/directions/MobileDevelopment.async";
export { Information } from "./Main/directions/Information.async";
export { Exploitation } from "./Main/directions/Exploitation.async";
export { AutoMechanic } from "./Main/directions/AutoMechanic.async";
export { News } from "./HeaderPages/news/News.async";
export { NewsCards } from "./HeaderPages/news/NewsCards.async";
export { LDocs } from "./HeaderPages/documents/LDocs.async";
export { About } from "./HeaderPages/about/About.async";
export { TeacherSl } from "./HeaderPages/teachersSlider/TeacherSl.async";
export { Masters } from "./HeaderPages/Masters.async";
export { Applicants } from "./HeaderPages/Applicants.async";
export { default as LoginPage } from "./admin/adminpages/LoginPage";
export { default as AdminPage } from "./admin/adminpages/AdminPage";
export { default as HomeAdmin } from "./admin/adminpages/HomeAdmin";
export { default as CoursesAdmin } from "./admin/adminpages/CoursesAdmin";
export { default as NpaAdmin } from "./admin/adminpages/NpaAdmin";
export { default as NewsAdmin } from "./admin/adminpages/NewsAdmin";
export { default as PlitAdmin } from "./admin/adminpages/PlitAdmin";
export { default as AboutAdmin } from "./admin/adminpages/AboutAdmin";
export { default as TeachersSlAdmin } from "./admin/adminpages/TeachersSlAdmin";
